apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment  # Nom de la ressource
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: <registry>/<username>/eureka-server:latest
        ports:
        - containerPort: 8010
