apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment  # Nom de la ressource
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practitioner-service
  template:
    metadata:
      labels:
        app: practitioner-service
    spec:
      containers:
      - name: practitioner-service
        image: <registry>/<username>/practitioner-service:latest
        ports:
        - containerPort: 8012
